[package]
name = "rust-roon-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
get_if_addrs = "0.5.3"
uuid = {version = "1.0.0", features = ["v4"]}
url = "2.2.2"
regex = "1.5.5"
tungstenite = "0.17.2"

[features]
pairing = []
status = []
settings = []
default = ["status"]
